# Generated by Django 2.2 on 2020-09-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdProof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images/id_proofs')),
            ],
            options={
                'db_table': 'id_proof',
            },
        ),
    ]
