# Generated by Django 2.2 on 2020-09-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utype', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'user_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=5)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=200)),
                ('pin', models.CharField(default='', max_length=6)),
                ('email', models.CharField(default='', max_length=200)),
                ('contact_no', models.CharField(default='', max_length=12)),
                ('alt_contact_no', models.CharField(default='', max_length=12)),
                ('password', models.CharField(default='', max_length=200)),
                ('date_of_bith', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='images/user/id_proofs')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('proof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_profile.IdProof')),
                ('utype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserType')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='ActivityHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(default='', max_length=50)),
                ('entity', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('time', models.TimeField()),
                ('activity_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'activity_history',
            },
        ),
    ]
