# Generated by Django 2.2 on 2020-09-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityhistory',
            old_name='activity_by',
            new_name='user',
        ),
    ]
