# Generated by Django 2.2 on 2020-09-13 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200912_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_bith',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/user/id_proofs'),
        ),
        migrations.AlterField(
            model_name='user',
            name='proof_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member_profile.IdProof'),
        ),
    ]
