# Generated by Django 2.2 on 2020-09-13 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200913_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='utype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserType'),
        ),
    ]
